# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=100)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
